version: '3.8'

services:
  # Maya API
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://maya:maya_password@postgres:5432/maya_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs

  # Maya Worker
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: worker
    environment:
      - DATABASE_URL=postgresql://maya:maya_password@postgres:5432/maya_db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=maya
      - POSTGRES_PASSWORD=maya_password
      - POSTGRES_DB=maya_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # n8n for automation
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
  n8n_data:
