services:
  - type: web
    name: maya-ai-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: maya-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: maya-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    autoDeploy: true
    healthCheckPath: /health

databases:
  - name: maya-postgres
    databaseName: maya
    user: maya

  - name: maya-redis
    plan: starter